version: '3'

services:
  postgres:
    env_file: ".env"
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      # https://stackoverflow.com/a/71986488/2521274
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
  
  # node:
  #   image: node
  #   # restart: always
  #   env_file: ".env"
  #   volumes:
  #     - ./packages/server:/app
  #   ports:
  #     - 5173:5173
  #     - 9229:9229
  #   depends_on:
  #     - postgres
  #   working_dir: /app
  #   command: bash -c "npm install && npm run debug"
    